CREATE DATABASE IF NOT EXISTS userdb;

FLUSH PRIVILEGES;

USE userdb;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    fname VARCHAR(255) NOT NULL,
    lname VARCHAR(255),
    email VARCHAR(255)    
)  ENGINE=INNODB;