version: '3.3'
services:
  web:
    image: tomcat:9.0.1-jre8-alpine  
    command: ["catalina.sh", "run"]
    ports:
      - "8888:8080"   
    volumes:
      - ./target/ReflectedXSS.war:/usr/local/tomcat/webapps/ReflectedXSS.war
      - ./context.xml:/usr/local/tomcat/conf/context.xml
      - ./catalina.properties:/usr/local/tomcat/conf/catalina.properties